---

- name: Downloading the Palantir WEF Configuration
  win_shell: ".\\download_palantir_wef.ps1"
  args:
    chdir: 'c:\vagrant\scripts'
  register: palantir_wef
  failed_when: "'Exception' in palantir_wef.stdout"
  changed_when: "' already exists. Moving On.' not in palantir_wef.stdout"

- debug: msg="{{ palantir_wef.stdout_lines }}"
  
- name: Installing osquery
  win_shell: ".\\install-osquery.ps1"
  args:
    chdir: 'c:\vagrant\scripts'
  register: install_osquery
  failed_when: "'Exception' in install_osquery.stdout"
  changed_when: "' already installed. Moving On.' not in install_osquery.stdout"

- debug: msg="{{ install_osquery.stdout_lines }}"

- name: Installing SysInternals Tools
  win_shell: ".\\install-sysinternals.ps1"
  args:
    chdir: 'c:\vagrant\scripts'
  register: sysinternals
  failed_when: "'Exception' in sysinternals.stdout"
  changed_when: "'Tools directory exists, no need to re-install.' not in sysinternals.stdout"

- debug: msg="{{ sysinternals.stdout_lines }}"

- name: Installing Velociraptor
  win_shell: ".\\install-velociraptor.ps1"
  args:
    chdir: 'c:\vagrant\scripts'
  register: velociraptor
  failed_when: "'Exception' in velociraptor.stdout"
  changed_when: "' already installed. Moving On.' not in velociraptor.stdout"

- debug: msg="{{ velociraptor.stdout_lines }}"

- name: Installing AutorunsToWineventlog
  win_shell: ".\\install-autorunstowineventlog.ps1"
  args:
    chdir: 'c:\vagrant\scripts'
  register: autorunstowineventlog
  failed_when: "'Exception' in autorunstowineventlog.stdout"
  changed_when: "' already installed. Moving On.' not in autorunstowineventlog.stdout"

- debug: msg="{{ autorunstowineventlog.stdout_lines }}"

- name: Installing Red Team Tooling
  win_shell: ".\\install-redteam.ps1"
  args:
    chdir: 'c:\vagrant\scripts'
  register: redteam
  failed_when: "'Exception' in redteam.stdout"
  changed_when: "' already installed. Moving On.' not in redteam.stdout"

- debug: msg="{{ redteam.stdout_lines }}"

- name: Install Utilities 
  win_chocolatey:
    name:
    - NotepadPlusPlus
    - GoogleChrome
    - WinRar
    - wireshark
    - winpcap
    state: present






